<nav id="navigation">

    <ul>

        <li> <a class="navlink " id="lftBut" href="index.php"> Home </a> </li>
        <li> <a class="navlink inBut" href="jobs.php"> Jobs </a> </li>
        <li> <a class="navlink inBut" href="apply.php"> Apply </a> </li>
        <li> <a class="navlink inBut" href="about.php"> About </a> </li>
        <li> <a class="navlink" id="inButEn" href="enhancements.php"> Enhancements </a> </li>
        <li> <a class="navlink" id="righBut" href="enhancements2.php"> Enhancements 2 </a> </li>


    </ul>

</nav>